// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySlicing(arg1) {
  return window['go']['main']['App']['ApplySlicing'](arg1);
}

export function Catalog() {
  return window['go']['main']['App']['Catalog']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetProgram(arg1) {
  return window['go']['main']['App']['GetProgram'](arg1);
}

export function GetSampleParams(arg1) {
  return window['go']['main']['App']['GetSampleParams'](arg1);
}

export function ImportSample(arg1) {
  return window['go']['main']['App']['ImportSample'](arg1);
}

export function InspectSlicing(arg1) {
  return window['go']['main']['App']['InspectSlicing'](arg1);
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function SetProgram(arg1, arg2) {
  return window['go']['main']['App']['SetProgram'](arg1, arg2);
}

export function SetSampleParams(arg1, arg2) {
  return window['go']['main']['App']['SetSampleParams'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
