// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {protocol} from '../models';

export function ApplySlicing(arg1:main.SlicingRequest):Promise<void>;

export function Catalog():Promise<main.Catalog>;

export function Connect(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Disconnect():Promise<void>;

export function GetProgram(arg1:number):Promise<protocol.ProgramJSON>;

export function InspectSlicing(arg1:main.SlicingRequest):Promise<main.SlicingPreflight>;

export function ListPorts():Promise<main.PortList>;

export function SetProgram(arg1:number,arg2:protocol.ProgramJSON):Promise<void>;

export function Status():Promise<main.ConnectionStatus>;
