// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {protocol} from '../models';

export function ApplySlicing(arg1:main.SlicingRequest):Promise<void>;

export function Catalog():Promise<main.Catalog>;

export function ClearWaveformCache():Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ConnectSerial(arg1:string,arg2:number):Promise<void>;

export function CopySampleAudio(arg1:number):Promise<Array<number>>;

export function Disconnect():Promise<void>;

export function GetCachedWaveform(arg1:number,arg2:string,arg3:number):Promise<Array<number>>;

export function GetDrum():Promise<protocol.DrumSettings>;

export function GetOverall():Promise<protocol.OverallSettings>;

export function GetProgram(arg1:number):Promise<protocol.ProgramJSON>;

export function GetSampleParams(arg1:number):Promise<protocol.SampleParams>;

export function ImportSample(arg1:string):Promise<main.ImportInfo>;

export function InspectSlicing(arg1:main.SlicingRequest):Promise<main.SlicingPreflight>;

export function ListPorts():Promise<main.PortList>;

export function OpenProgramJSON():Promise<protocol.ProgramJSON>;

export function PreviewMidi(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ProbeForS950():Promise<main.ProbeResult>;

export function PutCachedWaveform(arg1:number,arg2:string,arg3:number,arg4:Array<number>):Promise<void>;

export function ResampleSample(arg1:Array<number>,arg2:number,arg3:number):Promise<main.ResampledSample>;

export function SaveProgramJSON(arg1:protocol.ProgramJSON,arg2:string):Promise<string>;

export function SaveSampleWav(arg1:string,arg2:number,arg3:Array<number>):Promise<string>;

export function SendSample(arg1:number,arg2:Array<number>,arg3:number,arg4:protocol.SampleParams):Promise<void>;

export function SetDrum(arg1:protocol.DrumSettings):Promise<void>;

export function SetOverall(arg1:protocol.OverallSettings):Promise<void>;

export function SetProgram(arg1:number,arg2:protocol.ProgramJSON):Promise<void>;

export function SetSampleParams(arg1:number,arg2:protocol.SampleParams):Promise<void>;

export function Status():Promise<main.ConnectionStatus>;

export function VerifyDevice():Promise<void>;
