// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySlicing(arg1) {
  return window['go']['main']['App']['ApplySlicing'](arg1);
}

export function Catalog() {
  return window['go']['main']['App']['Catalog']();
}

export function ClearWaveformCache() {
  return window['go']['main']['App']['ClearWaveformCache']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function ConnectSerial(arg1, arg2) {
  return window['go']['main']['App']['ConnectSerial'](arg1, arg2);
}

export function CopySampleAudio(arg1) {
  return window['go']['main']['App']['CopySampleAudio'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetCachedWaveform(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCachedWaveform'](arg1, arg2, arg3);
}

export function GetDrum() {
  return window['go']['main']['App']['GetDrum']();
}

export function GetOverall() {
  return window['go']['main']['App']['GetOverall']();
}

export function GetProgram(arg1) {
  return window['go']['main']['App']['GetProgram'](arg1);
}

export function GetSampleParams(arg1) {
  return window['go']['main']['App']['GetSampleParams'](arg1);
}

export function ImportSample(arg1) {
  return window['go']['main']['App']['ImportSample'](arg1);
}

export function InspectSlicing(arg1) {
  return window['go']['main']['App']['InspectSlicing'](arg1);
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function OpenProgramJSON() {
  return window['go']['main']['App']['OpenProgramJSON']();
}

export function PreviewMidi(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewMidi'](arg1, arg2, arg3, arg4);
}

export function ProbeForS950() {
  return window['go']['main']['App']['ProbeForS950']();
}

export function PutCachedWaveform(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PutCachedWaveform'](arg1, arg2, arg3, arg4, arg5);
}

export function ResampleSample(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResampleSample'](arg1, arg2, arg3);
}

export function SaveProgramJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveProgramJSON'](arg1, arg2);
}

export function SaveSampleWav(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSampleWav'](arg1, arg2, arg3);
}

export function SendSample(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendSample'](arg1, arg2, arg3, arg4);
}

export function SetDrum(arg1) {
  return window['go']['main']['App']['SetDrum'](arg1);
}

export function SetOverall(arg1) {
  return window['go']['main']['App']['SetOverall'](arg1);
}

export function SetProgram(arg1, arg2) {
  return window['go']['main']['App']['SetProgram'](arg1, arg2);
}

export function SetSampleParams(arg1, arg2) {
  return window['go']['main']['App']['SetSampleParams'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function VerifyDevice() {
  return window['go']['main']['App']['VerifyDevice']();
}
