// Tests for the TS shim over the Go waveform cache.
//
// wordsToPcm is a pure math helper — directly tested.
// hydrateAllSamplesFromCache / persistSamplesToCache stub the Wails
// bindings via vi.mock so the cache lifecycle runs fully in-process.

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { get } from 'svelte/store';

// Per-key cached entries: tests pre-seed this map so GetCachedWaveform
// returns the right blob for a given (slot, name, totalWords). Misses
// resolve to null (the Go side's miss contract).
type CacheKey = string;
const cache = new Map<CacheKey, number[]>();
const keyOf = (slot: number, name: string, total: number) => `${slot}|${name}|${total}`;

vi.mock('../../../wailsjs/go/main/App', () => ({
  GetCachedWaveform: vi.fn((slot: number, name: string, total: number) =>
    Promise.resolve(cache.get(keyOf(slot, name, total)) ?? null),
  ),
  PutCachedWaveform: vi.fn((slot: number, name: string, total: number, words: number[]) => {
    cache.set(keyOf(slot, name, total), words);
    return Promise.resolve();
  }),
}));

import { samples, newLocalSample, type Sample } from './samples';
import {
  wordsToPcm,
  hydrateAllSamplesFromCache,
  hydrateSampleFromCache,
  persistSampleToCache,
  persistSamplesToCache,
} from './waveformcache';

beforeEach(() => {
  samples.set([]);
  cache.clear();
  vi.clearAllMocks();
});

// Helper: device sample without host audio (the fresh-from-catalog
// shape that hydration is supposed to fill in).
function deviceSample(slot: number, name: string, length: number): Sample {
  return { ...newLocalSample(slot, name, 44100, length), source: 'device' };
}

describe('wordsToPcm', () => {
  it('maps the 12-bit offset-binary midpoint to zero', () => {
    expect(wordsToPcm([0x800])).toEqual([0]);
  });

  it('scales to int16 range (matching ImportSample PCM convention)', () => {
    // 0xFFF → (4095 - 2048) << 4 = 2047 << 4 = 32752 (just shy of
    // INT16_MAX). 0x000 → (0 - 2048) << 4 = -32768 (INT16_MIN).
    // These values are what buildWaveformPaths' PCM_MAX=32768
    // divisor expects, so the rendered envelope reaches near full
    // amplitude on a hot signal.
    const pcm = wordsToPcm([0x000, 0xFFF]);
    expect(pcm[0]).toBe(-32768);
    expect(pcm[1]).toBe(32752);
  });

  it('is linear: doubling the offset doubles the magnitude', () => {
    const [a, b] = wordsToPcm([0x800 + 100, 0x800 + 200]);
    expect(b / a).toBeCloseTo(2, 5);
  });

  it('returns an empty array for empty input', () => {
    expect(wordsToPcm([])).toEqual([]);
  });
});

describe('hydrateSampleFromCache', () => {
  it('returns words + derived pcm on a hit', async () => {
    cache.set(keyOf(0, 'KICK', 4), [0x800, 0xC00, 0x800, 0x400]);
    const out = await hydrateSampleFromCache(deviceSample(0, 'KICK', 4));
    expect(out?.words12).toEqual([0x800, 0xC00, 0x800, 0x400]);
    expect(out?.pcm[0]).toBeCloseTo(0, 5);
    expect(out?.pcm[1]).toBeGreaterThan(0);
    expect(out?.pcm[3]).toBeLessThan(0);
  });

  it('returns null on a miss', async () => {
    const out = await hydrateSampleFromCache(deviceSample(7, 'GHOST', 100));
    expect(out).toBeNull();
  });

  it('treats Wails errors as misses (logs but does not throw)', async () => {
    // GetCachedWaveform isn't in the auto-generated App.d.ts yet —
    // it'll be regenerated by `wails dev` on next boot. For type
    // checking we cast through any.
    const App = await import('../../../wailsjs/go/main/App');
    ((App as any).GetCachedWaveform as ReturnType<typeof vi.fn>).mockImplementationOnce(
      () => Promise.reject(new Error('cache disk full')),
    );
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
    const out = await hydrateSampleFromCache(deviceSample(0, 'BOOM', 1));
    expect(out).toBeNull();
    expect(warn).toHaveBeenCalled();
    warn.mockRestore();
  });
});

describe('hydrateAllSamplesFromCache', () => {
  it('attaches cached audio only to matching device rows', async () => {
    samples.set([
      deviceSample(0, 'KICK', 4),
      deviceSample(1, 'SNARE', 4),
      newLocalSample(2, 'LOCAL', 44100, 4), // local: must be skipped
    ]);
    cache.set(keyOf(0, 'KICK', 4),  [0x800, 0x900, 0x800, 0x700]);
    cache.set(keyOf(1, 'SNARE', 4), [0x800, 0xA00, 0xB00, 0xC00]);

    await hydrateAllSamplesFromCache();

    const list = get(samples);
    expect(list[0].words12).toEqual([0x800, 0x900, 0x800, 0x700]);
    expect(list[0].pcm).toBeDefined();
    expect(list[1].words12).toEqual([0x800, 0xA00, 0xB00, 0xC00]);
    expect(list[2].words12).toBeUndefined(); // local row untouched
  });

  it('skips device rows that already have host audio', async () => {
    // Phase 1A's in-memory carry-over wins over a stale-on-disk
    // entry — we don't overwrite an existing pcm/words12.
    const existing = { pcm: [0.5], words12: [0xC00] };
    samples.set([
      { ...deviceSample(0, 'KICK', 1), ...existing },
    ]);
    cache.set(keyOf(0, 'KICK', 1), [0x000]); // wildly different
    await hydrateAllSamplesFromCache();
    const list = get(samples);
    expect(list[0].words12).toEqual([0xC00]); // unchanged
  });

  it('no-ops cleanly when nothing needs hydration', async () => {
    samples.set([newLocalSample(0, 'LOCAL', 44100, 4)]);
    const App = await import('../../../wailsjs/go/main/App');
    await hydrateAllSamplesFromCache();
    expect((App as any).GetCachedWaveform).not.toHaveBeenCalled();
  });

  it('skips slots with no cache entry while still hydrating ones that hit', async () => {
    samples.set([
      deviceSample(0, 'HIT', 2),
      deviceSample(1, 'MISS', 2),
    ]);
    cache.set(keyOf(0, 'HIT', 2), [0x800, 0xC00]);
    // slot 1 intentionally absent

    await hydrateAllSamplesFromCache();
    const list = get(samples);
    expect(list[0].words12).toEqual([0x800, 0xC00]);
    expect(list[1].words12).toBeUndefined();
  });
});

describe('persistSampleToCache / persistSamplesToCache', () => {
  it('writes host audio under the (slot, name, length) key', async () => {
    const s: Sample = {
      ...deviceSample(0, 'CACHED', 4),
      words12: [1, 2, 3, 4],
      pcm: [0, 0, 0, 0],
    };
    await persistSampleToCache(s);
    expect(cache.get(keyOf(0, 'CACHED', 4))).toEqual([1, 2, 3, 4]);
  });

  it('keys cache by words12.length, not sample.length', async () => {
    // Regression: at Apply-success time scanMemory hasn't refreshed
    // the SPRM yet, so sample.length is still the skinny default
    // (1) while words12 holds the real multi-thousand-word buffer.
    // Persisting under the skinny length wrote a file the Go
    // reader (correctly) rejected as ErrCorrupt on next session
    // because the body claimed N words while the lookup said 1.
    const s: Sample = {
      ...deviceSample(0, 'SKINNY', 1), // skinny length (placeholder)
      words12: [10, 20, 30, 40, 50],   // actual 5-word audio buffer
    };
    await persistSampleToCache(s);
    // Body-length key written, skinny-length key NOT.
    expect(cache.has(keyOf(0, 'SKINNY', 5))).toBe(true);
    expect(cache.has(keyOf(0, 'SKINNY', 1))).toBe(false);
  });

  it('no-ops when the sample has no words12', async () => {
    const App = await import('../../../wailsjs/go/main/App');
    await persistSampleToCache(deviceSample(0, 'NOAUDIO', 4));
    expect((App as any).PutCachedWaveform).not.toHaveBeenCalled();
  });

  it('persists every requested slot via the bulk helper', async () => {
    samples.set([
      { ...deviceSample(0, 'A', 2), words12: [1, 2] },
      { ...deviceSample(1, 'B', 2), words12: [3, 4] },
      { ...deviceSample(2, 'C', 2), words12: [5, 6] }, // not requested
    ]);
    await persistSamplesToCache([0, 1]);
    expect(cache.get(keyOf(0, 'A', 2))).toEqual([1, 2]);
    expect(cache.get(keyOf(1, 'B', 2))).toEqual([3, 4]);
    expect(cache.has(keyOf(2, 'C', 2))).toBe(false);
  });

  it('continues after a single-slot write failure', async () => {
    const App = await import('../../../wailsjs/go/main/App');
    ((App as any).PutCachedWaveform as ReturnType<typeof vi.fn>)
      .mockImplementationOnce(() => Promise.reject(new Error('boom')))
      .mockImplementationOnce((slot: number, name: string, total: number, words: number[]) => {
        cache.set(keyOf(slot, name, total), words);
        return Promise.resolve();
      });
    samples.set([
      { ...deviceSample(0, 'FAIL', 2), words12: [9, 9] },
      { ...deviceSample(1, 'OK',   2), words12: [1, 2] },
    ]);
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
    await persistSamplesToCache([0, 1]);
    // First write threw → no entry. Second still landed.
    expect(cache.has(keyOf(0, 'FAIL', 2))).toBe(false);
    expect(cache.get(keyOf(1, 'OK', 2))).toEqual([1, 2]);
    warn.mockRestore();
  });
});

describe('round trip: persist then hydrate', () => {
  it('next-session simulation — Apply writes, refresh reloads, hydrate restores', async () => {
    // 1. Apply Slicing wrote two slices into device slots 0 and 1.
    samples.set([
      { ...deviceSample(0, 'S_01', 3), words12: [0x800, 0xC00, 0x400] },
      { ...deviceSample(1, 'S_02', 3), words12: [0x800, 0x200, 0xE00] },
    ]);
    await persistSamplesToCache([0, 1]);

    // 2. Simulate app restart: catalog re-pulls fresh device rows
    //    with no host audio.
    samples.set([
      deviceSample(0, 'S_01', 3),
      deviceSample(1, 'S_02', 3),
    ]);

    // 3. Hydration on Connect.
    await hydrateAllSamplesFromCache();
    const list = get(samples);
    expect(list[0].words12).toEqual([0x800, 0xC00, 0x400]);
    expect(list[1].words12).toEqual([0x800, 0x200, 0xE00]);
    // PCM should be derived (non-empty) for both.
    expect(list[0].pcm?.length).toBe(3);
    expect(list[1].pcm?.length).toBe(3);
  });
});
